repos:
  # C/C++ formatting with clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6  # pick a stable clang-format version
    hooks:
      - id: clang-format
        args: [--style=file]   # uses your .clang-format
        files: \.(c|h|cpp|hpp)$

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        args: [--strict]
