name: Static Analysis

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy
      - name: Run clang-tidy
        run: clang-tidy pal/**/*.c -- -Ipal/include
